version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: bibliorate-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bibliorate
      MYSQL_USER: bibliorate_user
      MYSQL_PASSWORD: bibliorate_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
